language: node_js
node_js:
  - '8'
env:
  global:
cache:
  yarn: true
  directories:
    - node_modules
script:
  - lerna run --parallel lint
  - lerna run --parallel test
  - lerna run --parallel build
